export type {QueryFetcher, QueryArgs} from './QueryFetcher';
export {query$} from './QueryFetcher';
export type {DepartmentConnectionFetcher} from './DepartmentConnectionFetcher';
export {departmentConnection$, departmentConnection$$} from './DepartmentConnectionFetcher';
export type {DepartmentEdgeFetcher} from './DepartmentEdgeFetcher';
export {departmentEdge$, departmentEdge$$} from './DepartmentEdgeFetcher';
export type {DepartmentFetcher} from './DepartmentFetcher';
export {department$, department$$} from './DepartmentFetcher';
export type {NodeFetcher} from './NodeFetcher';
export {node$, node$$} from './NodeFetcher';
export type {EmployeeFetcher} from './EmployeeFetcher';
export {employee$, employee$$} from './EmployeeFetcher';
export type {PageInfoFetcher} from './PageInfoFetcher';
export {pageInfo$, pageInfo$$} from './PageInfoFetcher';
export type {EmployeeConnectionFetcher} from './EmployeeConnectionFetcher';
export {employeeConnection$, employeeConnection$$} from './EmployeeConnectionFetcher';
export type {EmployeeEdgeFetcher} from './EmployeeEdgeFetcher';
export {employeeEdge$, employeeEdge$$} from './EmployeeEdgeFetcher';
export type {MutationFetcher, MutationArgs} from './MutationFetcher';
export {mutation$} from './MutationFetcher';
